### Required, node's {ip:port} to connect.
system.peers=127.0.0.1:20200
### Required
system.groupId=1
### Optional. Default will search conf,config,src/main/conf/src/main/config
system.certPath=conf,config,src/main/resources/conf,src/main/resources/config
### Optional. If don't specify a random private key will be used
system.hexPrivateKey=abce280926debccedf8d7b6555b26353573e4cbfa11b4b23fc2cdca9559ddd49
### Optional. Please fill this address if you want to use related service
system.contract.workshopTwoAddress=0xcd3775b2ccce8f5fb108c53597b22bf81d5058d1
### Optional. Please fill this address if you want to use related service
system.contract.workshopThreeAddress=0x8ad7027e3277449c079ba03641165f76d2c1d3db
### Optional. Please fill this address if you want to use related service
system.contract.workshopOneAddress=0xf11054f8bc2e4d78a0ded5aa0ead04debc9401f4
### Optional. Please fill this address if you want to use related service
system.contract.workshopFourAddress=0x94fa2750dbf6fa43f7ca24f0e667b3e167133226
### Optional. Please fill this address if you want to use related service
system.contract.rawMaterialAddress=0x179396f45e1cde809780a7b077c026fcb317548f
### ### Springboot server config
server.port=8080
server.session.timeout=60
banner.charset=UTF-8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
